// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasl.Infrastructure.Persistence;

#nullable disable

namespace Wasl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WaslDbContext))]
    [Migration("20260828150057_ExplicitCollationOnSearchedCustomerColumns")]
    partial class ExplicitCollationOnSearchedCustomerColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("TicketNumberSeq", "dbo");

            modelBuilder.Entity("Wasl.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ActorRole")
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLog_Actor");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLog_Entity");

                    b.HasIndex(new[] { "OccurredAtUtc" }, "IX_AuditLog_NotSuccess")
                        .IsDescending()
                        .HasFilter("[Outcome] <> 'Success'");

                    b.HasIndex(new[] { "OccurredAtUtc" }, "IX_AuditLog_Time")
                        .IsDescending();

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_ChangesIsJson", "[Changes] IS NULL OR ISJSON([Changes]) = 1");
                        });
                });

            modelBuilder.Entity("Wasl.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customers_Contact", "[Email] IS NOT NULL OR [PhoneE164] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("EscalatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EscalationReason")
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Tickets_Customer");

                    b.HasIndex("EscalatedByUserId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Tickets_TicketNumber");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Tickets_Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId", "CreatedAtUtc")
                        .HasDatabaseName("IX_TicketComments_Ticket_Time");

                    b.ToTable("TicketComments", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketComments_Body", "LEN(LTRIM(RTRIM(Body))) > 0");
                        });
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.TicketHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TicketId", "PerformedAtUtc")
                        .HasDatabaseName("IX_TicketHistory_Ticket");

                    b.ToTable("TicketHistory", (string)null);
                });

            modelBuilder.Entity("Wasl.Domain.Users.SupportUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_SupportUsers_Email");

                    b.ToTable("SupportUsers", (string)null);
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("Wasl.Domain.Users.SupportUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tickets_Assignee");

                    b.HasOne("Wasl.Domain.Users.SupportUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tickets_CreatedBy");

                    b.HasOne("Wasl.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Customers");

                    b.HasOne("Wasl.Domain.Users.SupportUser", null)
                        .WithMany()
                        .HasForeignKey("EscalatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tickets_EscalatedBy");
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.TicketComment", b =>
                {
                    b.HasOne("Wasl.Domain.Users.SupportUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketComments_Author");

                    b.HasOne("Wasl.Domain.Tickets.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketComments_Tickets");
                });

            modelBuilder.Entity("Wasl.Domain.Tickets.TicketHistoryEntry", b =>
                {
                    b.HasOne("Wasl.Domain.Users.SupportUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TicketHistory_PerformedBy");

                    b.HasOne("Wasl.Domain.Tickets.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketHistory_Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
